sudo: required
services:
  - docker
addons:
   apt:
     sources:
       - git-core
     packages:
       - git

cache:
  directories:
    - $HOME/arquillian-blog
    - $HOME/.m2

branches:
    except:    
        - /^([0-9]+)\.([0-9]+)\.([0-9]+)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-]+)?$/

before_install:
  - pwd
  - ls
  - mkdir awestruct
before_script:
  - build_prod_and_run.sh --working-dir=$HOME/arquillian-blog
  - git clone git@github.com:MatousJobanek/arquillian.github.com-tests.git $HOME/arquillian-blog/arquillian.github.com-tests

script:
  - mvn clean install -f $HOME/arquillian-blog/ -Darquillian.blog.url=http://localhost:4242/ -Dbrowser=phantomjs
